FROM rocm/pytorch-private:rocm_6.0_12660_vllm_v3_70b_v2_jack
ENV WORKSPACE_DIR=/var/lib/jenkins
RUN mkdir -p $WORKSPACE_DIR
WORKDIR $WORKSPACE_DIR
# Limit arch's so composable kernel doesn't take days to finish
ENV PYTORCH_ROCM_ARCH=gfx90a;gfx940;gfx941;gfx942
RUN sed -i 's/, hipblaslt-dev \(.*\), hipcub-dev/, hipcub-dev/g' /var/lib/dpkg/status
RUN sed -i 's/, hipblaslt \(.*\), hipfft/, hipfft/g' /var/lib/dpkg/status
RUN git clone -b vllm_mi300_v4 https://streamhsa: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@github.com/ROCmSoftwarePlatform/SLOT.git
RUN apt remove -y hipblaslt
RUN cd ${WORKSPACE_DIR} && \
   rm -rf hipBLASLt && \
   git clone -b develop https://github.com/ROCmSoftwarePlatform/hipBLASLt && \
   cd hipBLASLt && \
   ./install.sh -idc --architecture 'gfx90a;gfx940;gfx941;gfx942' &&\
   cd ../ && rm -rf hipBLASLt
RUN git clone -b N1 https://streamhsa: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@github.com/amgddm/rocBLAS-internal.git && \
    cd rocBLAS-internal && ./install.sh -idc -a 'gfx90a;gfx940;gfx941;gfx942' &&\
    cd ../ && rm -rf rocBLAS-internal
RUN pip uninstall -y gradlib vllm
RUN rm -rf $WORKSPACE_DIR/vllm && rm -rf $WORKSPACE_DIR/gradlib
RUN mv $WORKSPACE_DIR/SLOT/projects/vllm $WORKSPACE_DIR
RUN mv $WORKSPACE_DIR/SLOT/projects/gradlib $WORKSPACE_DIR
RUN rm -rf $WORKSPACE_DIR/SLOT
RUN cd $WORKSPACE_DIR/gradlib &&\
    python setup.py develop
RUN cd $WORKSPACE_DIR/vllm/ &&\
    pip install -r requirements.txt &&\
    pip install typing-extensions==4.8.0 &&\
    python setup.py build && python setup.py develop; exit 0
ENV PYTHONPATH=$WORKSPACE_DIR/gradlib

RUN pip uninstall -y triton
RUN git clone https://github.com/ROCmSoftwarePlatform/triton.git && \
    cd triton/python && pip3 install -e .
# RUN git clone -b N1 https://streamhsa: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@github.com/amgddm/rocBLAS-internal.git && \
#     cd rocBLAS-internal && ./install.sh -idc -a gfx942 &&\
#     cd ../ && rm -rf rocBLAS-internal

COPY run_vllm.sh $WORKSPACE_DIR/
COPY run_vllm_tp1.sh $WORKSPACE_DIR/
COPY run_vllm_tp2.sh $WORKSPACE_DIR/
COPY run_vllm_tp4.sh $WORKSPACE_DIR/
COPY run_vllm_tp8.sh $WORKSPACE_DIR/
